language: node_js

node_js:
  - '11.6.0'

before_install:
  - echo -e "machine github.com\n  login $GITHUB_OAUTH_TOKEN" > ~/.netrc
after_success:
  - "npm version patch -m 'chore: Update version to %s'"
  - npm run build
  - npm run copy
before_deploy:
  - cd lib
deploy:
  - provider: npm
    email: ti@vitta.me
    skip_cleanup: true
    edge: true
    api_key:
      secure: ${VITTA_KEY_NPM}
  - provider: releases
    api_key:
      secure: ${GITHUB_OAUTH_TOKEN}
    file_glob: true
    file: ./*
    skip_cleanup: true
    draft: true
after_deploy:
  - cd ..
  - git push origin master
  - git push --tags

stages:
  - name: deploy
    if: branch = master
  - name: after_deploy
    if: branch = master
  - name: before_deploy
    if: branch = master

