language: node_js

node_js:
  - '11.6.0'

script: true

after_success:
  - npm version patch -m "Updating to %s"
  - npm install
  - npm run build
  - npm run copy
  - git push origin master
  - git push --tags
before_deploy:
  - cd lib
deploy:
  provider: npm
  email: ti@vitta.me
  skip_cleanup: true
  edge: true
  api_key:
    secure: ${VITTA_KEY_NPM}
  on:
    branch: master
    tags: true
    repo: vitta-health/attiv
