language: node_js

node_js:
  - '11.6.0'

after_success:
  - npm version patch -m "Updating to %s"
  - npm run build
  - npm run copy
before_deploy:
  - cd lib
deploy:
  if: branch = master
  provider: npm
  email: ti@vitta.me
  skip_cleanup: true
  edge: true
  api_key:
    secure: ${VITTA_KEY_NPM}
  on:
    branch: master
    tags: true
    repo: vitta-health/attiv
after_deploy:
  if: branch = master
  - git push origin master
  - git push --tags


