language: node_js

node_js:
  - '11.6.0'

script: 'true'

after_success:
  - npm run build #make a dist folder
before_deploy:
  - cd lib
deploy:
  provider: npm
  email: elvis.souza@vitta.me
  skip_cleanup: true
  api_key:
    secure: ${VITTA_KEY_NPM}
  on:
    branch: master
    tags: true
    repo: vitta-health/attiv-framework
