version: '3.1'

services:
  db:
    image: mysql:5.7
    container_name: attiv_db
    command: --sql-mode="" --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=attiv123
      - MYSQL_DATABASE=attiv
      - MYSQL_USER=attiv
      - MYSQL_PASSWORD=attiv
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata: